# Generated by Django 2.1.2 on 2018-12-13 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ascensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ascensor', models.IntegerField()),
                ('Modelo', models.CharField(max_length=20)),
                ('Fallas', models.CharField(max_length=60)),
                ('Reparaciones', models.CharField(max_length=60)),
                ('Piezasremplazadas', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=35)),
                ('Apellido', models.CharField(max_length=35)),
                ('Direccion', models.CharField(max_length=35)),
                ('Ciudad', models.CharField(max_length=35)),
                ('Comuna', models.CharField(max_length=20)),
                ('Telefono', models.IntegerField()),
                ('Correo', models.EmailField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Folio', models.IntegerField()),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Fechatermino', models.DateTimeField()),
                ('Ascensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Ascensor')),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Cliente')),
            ],
        ),
    ]
